# Unsafe save:
# When it's true, stats will be saved when
# player leaves (when MySQL is enabled), or
# when server disables.
# However, when false, it will save when
# player finds a reward.
# -----------------------------------
# If hide-found-blocks is "NONE", it will
# be disabled.
# -----------------------------------
# For custom skulls for find effect,
# use the Base64 Encoding
# from heads.freshcoal.com in the give command,
# what usually looks like this:
# eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzAxNDYxOTczNjM0NTI1MTk2ZWNjNzU3NjkzYjE3MWFkYTRlZjI0YWE5MjgzNmY0MmVhMTFiZDc5YzNhNTAyZCJ9fX0=
# -----------------------------------
# You can use DISABLED or NONE for some
# paths to disable it.
# -----------------------------------

placeholderapi: true
use-mysql: false
enabled: true
disabled-msg: '&cBlocks aren''t enabled yet! If you are a player, refer to a Server
  Administrator!'
use-uuid: true
check-full-inventory: 0
full-inventory-msg: '&c&lYour inventory is full!'
mysql-host: host
mysql-database: database
mysql-username: username
mysql-password: password
mysql-unsafe-save: true
no-permission: '&cYou don''t have permission for this!'
hide-found-blocks: NONE
blocks:
- -1924;4;-371;world
- -1964;45;-287;world
- -1111;71;115;world
- -921;69;1143;world
- 189;105;-761;world
- -300;124;-1078;world
- -1162;78;304;world
- -1795;79;934;world
- -1115;69;603;world
- -92;95;-758;world
- -813;152;-797;world
- -375;154;-747;world
- -1317;103;-763;world
- -1466;80;-32;world
- -1467;84;10;world
- -1127;72;-178;world
- -1446;77;231;world
- 157;125;-1035;world
- -1403;66;606;world
- -1337;97;1077;world
- -1305;131;1272;world
- -1359;80;487;world
- -1110;72;940;world
- -1105;84;866;world
- -1467;56;752;world
- -1095;83;1270;world
- -981;91;-550;world
- -371;99;-568;world
- -1372;105;903;world
- -715;113;-144;world
find-block-commands:
- particle mobSpell %locX% %locY% %locZ% 0.25 0.25 0.25 1 10
- msg %player% &bYou have found an easter egg!
- msg %player% &bYou have been awarded 1 rare crate!
- msg %player% &bYou have &f%blocksLeft%&b easter eggs left to find!
- pcrate give %player% rare 1
all-blocks-found-commands:
- broadcast &d%player% &bhas &efound &aall &6the &ceaster &feggs!
- msg %player% &bYou have been awarded 2 pure crates!
- pcrate give %player% pure 2
- minecraft:give %player% minecraft:potion 1 0 {CustomPotionEffects:[{Id:3,Amplifier:4,Duration:12000}],CustomPotionColor:16051518,display:{Name:"Ultimate Potion Of Haste",Lore:["Use an Eff 5 iron axe","or an Eff 6 diamond pick","for instant mining"]}}
already-found-commands:
- msg %player% &bYou have already found this easter egg
already-found-all-blocks:
- msg %player% &bYou have already found every easter egg
find-effect:
  enabled: true
  invisible: true
  small: true
  custom-name: ''
  head: PUMPKIN
  chest: NONE
  leg: NONE
  boot: NONE
  particle: FLAME
  loop: 30
  levitation-per-loop: 0.2
  yaw-rotation: 20
  scheduler: 2
  y-start: 0.25
  sound: ENTITY_FIREWORK_LAUNCH
  sound-pitch: 0
  disappear-commands:
    enabled: false
    commands:
    - say The find effect disappeared at %locX% %locY% %locZ%!
particles:
  loop: 20
  enabled: true
  found:
    dx: 0.05
    dy: 0.05
    dz: 0.05
    speed: 0.1
    quantity: 20
    type: FLAME
  notfound:
    dx: 0.05
    dy: 0.05
    dz: 0.05
    speed: 0.1
    quantity: 35
    type: DISABLED
